# Generated by Django 5.1.4 on 2025-01-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitemtag',
            name='news_item',
            field=models.ManyToManyField(related_name='tags', to='news_api.newsitem'),
        ),
    ]
