# Generated by Django 5.1.4 on 2025-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_newsitem_options_newsitemtag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
